name: flix_app
description: "FLIX - Ứng dụng Tra cứu Phim (Movie Lookup App)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  http: ^1.2.2
  provider: ^6.1.5+1
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.5
  image_picker: 1.2.3
  crop_your_image: 2.0.0
  image: 4.9.1
  web: ^1.1.1
  youtube_player_iframe: ^5.2.2
  share_plus: ^12.0.2
  sentry_flutter: 9.27.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome/welcome_background.jpg
